name: test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - master
    paths:
      - "**/*.ts"
      - ".github/workflows/test.yml"
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - name: Type check
        run: deno task check
